version: '3'


services:
  backend:
    container_name: backend
    build: ../../Downloads/SkyArchive/app
    command: >
      /bin/sh -c "go run"
    volumes:
      - ./app/:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    networks:
      - minio_backend
    depends_on:
      - db
      - minio

  frontend:
    container_name: frontend
    build: ../../Downloads/SkyArchive/client
    volumes:
      - ./client/:/client
    ports:
      - 5173:5173
    networks:
      - minio_backend
    depends_on:
      - backend

  db:
    container_name: db
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=flycloud
      - POSTGRES_PASSWORD=flycloud
      - POSTGRES_DB=flycloud_dev
  
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
        MINIO_ROOT_USER: "minio"
        MINIO_ROOT_PASSWORD: "minio123"
    volumes:
      - ./minio-cache:/data
    networks:
      - minio_backend
    command: app --console-address ":9001" /data

  nginx:
    container_name: nginx
    build: ../../Downloads/FlyCloud-connect/nginx
    ports:
      - 8080:8080
    networks:
      - minio_backend
    depends_on:
      - backend
      - frontend


networks:
  minio_backend:
    driver: bridge

volumes:
  postgres_data:
